name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: zzlw/ts-axios-doc@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: zzlw/vuepress-deploy-demo-target
        TARGET_BRANCH: master
        BUILD_SCRIPT: npm i && npm run docs:build
        BUILD_DIR: dist
