name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: zzlw/vuepress-deploy-demo-target@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: zzlw/ts-axios-doc
        TARGET_BRANCH: master
        BUILD_SCRIPT: npm i && npm i docs:build
        BUILD_DIR: dist
